web:              bin/server
queue:            bin/rake jobs:work
#queue-default:    bundle exec bin/delayed_job --pool=default,every1min run
#queue-default: bundle exec bin/delayed_job --queue=default run
#queue-registries: bundle exec bin/delayed_job --queue=registries run
#queue-every1min: bundle exec bin/delayed_job --queue=every1min run
#queue-instances:  bundle exec bin/delayed_job --queue=instances run

